---
# https://github.com/google/yamlfmt/blob/main/docs/config-file.md
# go install github.com/google/yamlfmt/cmd/yamlfmt@latest
continue_on_error: false
doublestar: false
exclude: []
extensions:
  - yaml
  - yml
# Use gitignore files for exclude paths. This is in addition to the patterns from the exclude option.
gitignore_excludes: true # default: false
gitignore_path: .gitignore
include: []
line_ending: lf
match_type: standard
output_format: default
regex_exclude: []
formatter:
  array_indent: 0
  disable_alias_key_correction: false
  disallow_anchors: false
  drop_merge_tag: false
  eof_newline: false
  force_array_style: ""
  force_quote_style: ""
  # Include --- at document start.
  include_document_start: true # default: false
  indent: 2
  indent_root_array: false
  indentless_arrays: false
  line_ending: lf
  max_line_length: 0
  pad_line_comments: 1
  retain_line_breaks: false
  # (NOTE: Takes precedence over retain_line_breaks) Retain line breaks in formatted YAML, but only keep a single line in groups of many blank lines.
  retain_line_breaks_single: true # default: false
  # Option that will preserve newlines in folded block scalars (blocks that start with >).
  scan_folded_as_literal: true # default: false
  strip_directives: false
  trim_trailing_whitespace: false
  type: basic
